### ISSUE TITLE
package can't etablish a connexion to database

### ISSUE THREAD

**Issue by thibaultvanc** [serverfireteam/blog#10]
Hello there,

I would like to use the blog system. Bur I have a problem running :  php artisan blog:install
![1ca7b5a21f67ac85683e3ac21b977c00](https://cloud.githubusercontent.com/assets/10731886/12609050/c0722896-c4df-11e5-9780-6b202e806e70.png)

It seems to be a pb to connect to the database, my application is correctly connect to my database, I don't undersant why the package can't etablish a connexion.

Thank you

**Comment by quant-algo** [comment]
@thibaultvanc it use same connection as the app , check your mysql and try again , it should work

**Comment by thibaultvanc** [comment]
Thank you for your reply !
My connection to database is correct... I use it in laravel Homestead. It's maybe that ?

**Comment by quant-algo** [comment]
I have found the problem of yours , you are trying to run the command out site of homestead , executing the commands inside your virtual machine and it should work

**Comment by thibaultvanc** [comment]
Yes !!!
I have connected with SSH and It works

Many Thanks

**Comment by quant-algo** [comment]
Send me a mail when you have any laravel problem and i will help you , support@serverfire.net
