### ISSUE TITLE
CSS Linking?

### ISSUE THREAD

**Issue by notflip** [serverfireteam/blog#5]
I see in your views that you link to your assets in the following way:

```
<link href="{{asset("packages/serverfireteam/blog/libs/syntaxhighlighter/styles/shCore.css")}}" rel="stylesheet" type="text/css" />
```

Won't this break? Since we won't have the packages/ folder but it will be in the vendor folder?

**Comment by quant-algo** [comment]
@notflip if you don't need code high lighter just remove it from your view , 

when you install the package it would put this files in your public folder
