### ISSUE TITLE
Wiews File

### ISSUE THREAD

**Issue by ghost** [serverfireteam/blog#8]
Hi.

I instal blog package. And my views files are in appfolder/vendor/serverfireteam/blog/src/views
I wound like to be in appfolder/resources/views 

Actually there are there, but can not make any changes on this views path. Only on  appfolder/vendor/serverfireteam/blog/src/views

Hove I set to make views changes in appfolder/resources/views

Tnx a lot

**Comment by quant-algo** [comment]
@NikolaGrdanjski  it should load from your folder after publish , if not check here : https://github.com/serverfireteam/blog/blob/master/src/Serverfireteam/Blog/BlogServiceProvider.php#L39 to see if there is problem

**Comment by ghost** [comment]
Thank for quick response.
I check the BlogServiceProvider.php#L39 and everything looks right. But simply not working.

eg. I delete all content in /resources/views/index.blade.php and I go to chech http://localhost:8000/blog
and everything is alright.

But I delete all content in /vendor/serverfireteam/blog/src/views/index.blade.php and chech http://localhost:8000/blog this time page is blank.

Which would mean that blog is rendering views from /vendor/serverfireteam/blog/src/views/ folder.

Tnx

**Comment by quant-algo** [comment]
@NikolaGrdanjski  you know laravel first look at the app folder if file are there will use that and if you delete them will use view in vendor , try to publish view and change them to see if it work

**Comment by ghost** [comment]
Thank you. I try to publish my app. 

But I have one more question.
I use blog package, and I wanted to modify view template.

Hove I can add header and footer to blog template? Header and footer are placed in /resources/views/includes/ 

I men this header and footer are parts of my web app. And i wante change blog header and footer with my header and footer desing.

Tnx a lot

**Comment by quant-algo** [comment]
run this command in cmd 

php artisan vendor:publish 

and edit  /resources/views/blog/index.blade.php

**Comment by ghost** [comment]
Thank you. Have nice day!
