### ISSUE TITLE
will this work in laravel 5.2, i tried got error

### ISSUE THREAD

**Issue by rameshreddyvemula** [serverfireteam/blog#9]
getting error with this command,  "php artisan blog:install" 
shall i use this "    'Serverfireteam\Blog\BlogServiceProvider'   " in app.php as provider or need to change  ??

**Comment by quant-algo** [comment]
@rameshreddyvemula we don't have laravel 5.2 version yet , sorry , you could send pull request

**Comment by larasoft-io** [comment]
@serverfire Do you plan to update to L5.2?  Do you know when you might put this out? Thanks

**Comment by quant-algo** [comment]
@ajs87 as laravelpanel now support laravel 5.2 , i'm going to release new version for laravel 5.2 today

**Comment by quant-algo** [comment]
@rameshreddyvemula @ajs87 install from 2.\* and it work with laravel 5.2
